### ISSUE TITLE
Error in simpleknn 

### ISSUE THREAD

**Issue by zuacubd** [li-xirong/hierse#1]
I am getting the following error. It seems "libsearch.so" file is missing in the "simpleknn/cpp" directory. Would you please check?

arif@gpu01:~/deeplearning/hierse$ python -c "from simpleknn.bigfile import BigFile"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/arif/deeplearning/simpleknn/simpleknn.py", line 12, in <module>
    libsearch = CDLL(os.path.join(os.path.dirname(**file**), "cpp", "libsearch.so"))
  File "/usr/lib/python2.7/ctypes/**init**.py", line 365, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: /home/arif/deeplearning/simpleknn/cpp/libsearch.so: cannot open shared object file: No such file or directory

**Comment by li-xirong** [comment]
hi, you may need to re-compile simpleknn before using it:
cd simpleknn
./build.sh

the above script shall generate cpp/libsearch.so
