### ISSUE TITLE
File Format for Pretrained Word2Vec

### ISSUE THREAD

**Issue by rjkrnkmr** [li-xirong/hierse#10]
Hi @li-xirong ,

In the pretrained word2vec model provided by you in the folder "/flickr4m/word2vec/tagvec500" has 3 different files feature.bin, id.txt and shape.txt. Also from your research paper i noticed that the flickr tags were trained using the Word2Vec tool. 

When i tried to trian my own tags i using Word2Vec tool and I could only generate something like "feautre.bin" file.
But your code is also dependant on id.txt and shape.txt files...

Could you please tell me how exactly can i generate them ?  or did you use any other method to generate them?

Regards

Raj

**Comment by li-xirong** [comment]
hi, basically two steps, 

Step 1. Export your trained word2vec models (whatever code used) as a plain text file, say ```id.feature.txt```, where each line starts with a word followed by its word2vec vector, using white space as separator. Suppose the vector has a dimension of 500, then each line shall have 501 columns.

Step 2. Process the text file by [txt2bin.py](https://github.com/li-xirong/jingwei/blob/master/util/simpleknn/txt2bin.py), something like
```bash
python txt2bin.py 500 id.feature.txt 0 result_folder
```
This will generate the three wanted files, i.e., *id.txt*, *shape.txt* and *feature.bin*, in the ```result_folder```. In particular, if your word2vec model contains ```n``` distinct words, the shape.txt file will have a single line of ```n 500```, while the ```id.txt``` will have ```n``` elements in one line.

**Comment by rjkrnkmr** [comment]
Hi @li-xirong ,

Many thanks for the detailed steps. I have 2 more queries.

1. I am using the [https://github.com/li-xirong/hierse/blob/master/tagging-new-image.md] steps to tag a own image and own tags using Tensorflow. I would like to evaluate this process,So can please provide some more detailed explanation of using **evaluate.py** to report the hit (As you have mentioned in the step 4 of your tutorial) 

2. I tried searching for **wnid2words.pkl** from Imagenet Website,But i couldn't find any related sources,Was it created by your own.? Or can i avail it from the ImageNet Website?

**Comment by li-xirong** [comment]
A1.  [evalutate.py](https://github.com/li-xirong/hierse/blob/master/evaluate.py) is tailored for the imagenet data, were ground-truth synset ID is included in image ID:  {$wnid}_{$suffix}. You may consider write your own evaluate code or re-write the ```load_ground_truth``` function w.r.t. your own data https://github.com/li-xirong/hierse/blob/a5534cb374284e3e7f18799d161663ca35d4baca/evaluate.py#L50

A2. The pickle file is available at the [data](https://github.com/li-xirong/hierse/tree/master/data) folder, loaded using
https://github.com/li-xirong/hierse/blob/a5534cb374284e3e7f18799d161663ca35d4baca/synset2vec.py#L26
