### ISSUE TITLE
Problem loading he pretrained word2vec file

### ISSUE THREAD

**Issue by rap9430** [li-xirong/hierse#2]
I cannot load the pretrained flickr4m file (feature.bin) neither by using the original word2vec excutable nor  by the gensim's module. Is there any hint?

**Comment by li-xirong** [comment]
The feature.bin file is read by [bigfile](https://github.com/li-xirong/simpleknn/blob/master/bigfile.py)

``` python
>>> from simpleknn.bigfile import BigFile
>>> feat_file = BigFile('flickr4m/word2vec/tagvec500')
[BigFile] 382298x500 instances loaded from flickr4m/word2vec/tagvec500
>>> [words,vecs] = feat_file.read(['cat', 'dog', 'xxxxxxxxx'])
>>> words, len(vecs), len(vecs[0])
(['dog', 'cat'], 2, 500)
```
