### ISSUE TITLE
Flickr4m names...

### ISSUE THREAD

**Issue by rap9430** [li-xirong/hierse#3]
I managed to read the labels from the flickr4m file. The command "feat_file.names" returns a list of tags. Many of them are a concatenation of individual tags (e.g. 10millionphotos, southamerica, theunforgettablepictures, superbmasterpiece etc.). Could i retrieve the actual tags? If not, then how did you encode those (long) tags?

**Comment by li-xirong** [comment]
We did not merge these long tags. They were in Flickr tag data upon which the word2vec model was trained. To decompose them, you may consider matching with another Flickr tag collection.
