### ISSUE TITLE
how to test a demo.jpg?

### ISSUE THREAD

**Issue by shinebay** [li-xirong/hierse#5]
as a newbie, how can I test tagging a jpg. for example, tagging a image: little-cat.jpg? thank you

**Comment by li-xirong** [comment]
You need a pre-trained (CNN) model that takes the image as input and outputs probabilistic scores of  the [1K ILSVRC12 labels](https://github.com/li-xirong/hierse/blob/master/data/synset_words_ilsvrc12_test1k.txt). Please see the [tutorial](https://github.com/li-xirong/hierse/blob/master/tutorial.md) page.
