### ISSUE TITLE
how to train hierse to output tags cloud like imagga or clarifai?

### ISSUE THREAD

**Issue by shinebay** [li-xirong/hierse#6]
![image](https://user-images.githubusercontent.com/7820385/33114226-e3bb1bd2-cf96-11e7-923f-13834b1985f7.png)
the above image in clarifai:[https://clarifai.com](https://clarifai.com) give me the tag results: mountain, no person, nature, landscape, travel, snow, outdoors, scenic, sky, mountain peak. In imagga:[https://imagga.com](https://imagga.com) it give me the tag results: mountain, glacier, snow, range, landscape
, mountains, peak, alp, sky, winter. So how can I train hierse to output tags cloud like imagga or clarifai?

**Comment by li-xirong** [comment]
hierse assumes the novel label set $Y_1$ is a subset of the ImageNet concepts. So for computing the w2v vector for a given label, the [PartialSynset2Vec](https://github.com/li-xirong/hierse/blob/master/synset2vec.py) takes wnid (wordnet-id) as input:
```python
    def _mapping(self, wnid):
        words = self.wnid2words[wnid].lower().split(',')
        res = []
        for word in words:
            res += word.strip().replace('-', '_').split()

        word_vecs = []
        for w in res:
            vec = self.word2vec.read_one(w)
            if vec:
                word_vecs.append(vec)

        if len(word_vecs)>0:
            return np.array(word_vecs).mean(axis=0)
        else:
            return None
```

To handle tags as you provided, you need to implement a subclass of `PartialSynset2Vec` and override the `_mapping` method accordingly. Something like

```python
    def _mapping(self, tag):
        words = tag.split()
        res = []
        for word in words:
            res += word.strip().replace('-', '_').split()

        word_vecs = []
        for w in res:
            vec = self.word2vec.read_one(w)
            if vec:
                word_vecs.append(vec)

        if len(word_vecs)>0:
            return np.array(word_vecs).mean(axis=0)
        else:
            return None
```
