### ISSUE TITLE
Training for a new custom image dataset and tags

### ISSUE THREAD

**Issue by abhigoku10** [li-xirong/hierse#7]
hi @li-xirong @mabirck  First of thanks for sharing this wonderful work i am really gratefull to you ppl . 
I am ne to this topic so i have few questions with this 
1. Can i train with my custom image dataset and tags if so what is the procedure to follow 
2.how to measure the performance of the model 

Can you pls be grateful to give some insight on the training part Thanking in advance

**Comment by li-xirong** [comment]
https://github.com/li-xirong/hierse/issues/6
