### ISSUE TITLE
Tensor flow Zero Shot tagging

### ISSUE THREAD

**Issue by rjkrnkmr** [li-xirong/hierse#8]
Hi @li-xirong,

I am using the baseline of your code and trying to execute the tensor flow with hierse, but it seems that "Use tensorflow to obtain prediction scores for $Y_0$" this part of code is not functioning.

The code gets stuck at the line:

names = imagenet.create_readable_names_for_imagenet_labels()

And when I try to debug itseems that the base URL on the tensor flow-slim model(Imagenet.py) is not valid or not fetching any data!

It throws me an error that "IOError: [Errno socket error] [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:726)"

Could you please tell me more about this/ fix this issue?

Thank you,

Regards

Raj

![image](https://user-images.githubusercontent.com/33498870/42311544-620578d6-803e-11e8-8979-ed73dfe43699.png)

![image](https://user-images.githubusercontent.com/33498870/42311695-bfa31296-803e-11e8-9e93-17890cae128b.png)

**Comment by li-xirong** [comment]
hi, indeed the url for the imagenet labels seems broken. This issue can be fixed by first downloading to your local computer the following two files from https://github.com/tensorflow/serving/tree/master/tensorflow_serving/example
+ ```imagenet_lsvrc_2015_synsets.txt``` 
+ ```imagenet_metadata.txt```

Then, replace with your own ```create_readable_names``` function
```python
names = create_readable_names_local()
```

**Comment by rjkrnkmr** [comment]
Hi,

Yes, I followed the steps and i could fix it. Thanks for the suggestions!
