### ISSUE TITLE
Wordnet and Flickr tags

### ISSUE THREAD

**Issue by rjkrnkmr** [li-xirong/hierse#9]
Hi,

I read the paper of HierSE and i could come to a conclusion that HierSE has used the hierarchy from Word Net.
Also in the ReadME file it was mentioned that there exist a pre-trained Word2Vec Model for flickr tags.

My question is was the model trained on Word-Net along with flickr tags?  or just with the flicker tags

Could you please tell me about how exactly is the Unsupervised(Pre-trained Word2Vec Model) influenced by the word net hierarchy and flickr tags?

Regards

Raj

**Comment by li-xirong** [comment]
the word2vec model was trained on the Flickr tags.
